version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.1.0
  aws-eb-cli: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    executor: node/default
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Front-end Install
          command: |
            npm run front:install
      - run:
          name: Back-end Install
          command: |
            npm run back:install
      - run:
          name: Front-end Build
          command: |
            npm run front:build
      - run:
          name: Back-end
          command: |
            npm run back:build
      - run:
          name: Deploy Front-end
          command: |
            npm run front:deploy
      - run:
          name: Deploy back-end
          command: |
            npm run back:deploy
workflows:
  udagram:
    jobs:
      - build:
        filter:
          branches:
            only:
              - master
